message

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -24,16 +24,27 @@ workflows:
           cd android
           ./gradlew app:assembleAndroidTest
           ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/integration_test/app_test.dart"
+      - name: Debug: Print GCLOUD_KEY_FILE length
+        script: |
+          echo "Length of GCLOUD_KEY_FILE: ${#GCLOUD_KEY_FILE}"
+          if [ -z "$GCLOUD_KEY_FILE" ]; then
+            echo "Error: GCLOUD_KEY_FILE is not set or is empty"
+            exit 1
+          fi
       - name: Run Firebase Test Lab Tests
         script: |
           set -ex
-          echo ${GCLOUD_KEY_FILE?} > ./gcloud_key_file.json
+          echo $GCLOUD_KEY_FILE | base64 --decode > ./gcloud_key_file.json
           gcloud auth activate-service-account --key-file=gcloud_key_file.json
           gcloud --quiet config set project $FIREBASE_PROJECT
-
-      - gcloud firebase test android run --type instrumentation --app ./build/app/outputs/apk/debug/app-debug.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
+          gcloud firebase test android run \
+            --type instrumentation \
+            --app build/outputs/apk/debug/app-debug.apk \
+            --test build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
+            --timeout 3m
     artifacts:
-      - build/**/outputs/**/*.apk
-      - build/**/outputs/**/*.aab
-      - build/**/outputs/**/mapping.txt
-      - flutter_drive.log
+      files:
+        - build/**/outputs/**/*.apk
+        - build/**/outputs/**/*.aab
+        - build/**/outputs/**/mapping.txt
+        - flutter_drive.log
